require("core.packer_config.colorscheme")
require("core.packer_config.nvim_tree")
require("core.packer_config.lualine")
require("core.packer_config.telescope")
require("core.packer_config.treesitter")
